spring.application.name=notes

spring.datasource.url=${NOTES_DATABASE_URL:jdbc:postgresql://localhost:5432/notes_dev}
spring.datasource.username=${NOTES_DATABASE_USERNAME:notes_dev}
spring.datasource.password=${NOTES_DATABASE_PASSWORD:notes_dev_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
